[project]
name = "emoji_use_mcp"
version = "0.1.0"
description = "MCP server for Emoji Usage"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.13.1",
    "pandas>=2.3.2",
    "pydantic>=2.11.7",
]
